# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(701, 291)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox1.setGeometry(QtCore.QRect(10, 10, 201, 111))
        self.groupBox1.setObjectName("groupBox1")
        self.btn1_1 = QtWidgets.QPushButton(self.groupBox1)
        self.btn1_1.setGeometry(QtCore.QRect(10, 30, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn1_1.setFont(font)
        self.btn1_1.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.btn1_1.setCheckable(False)
        self.btn1_1.setObjectName("btn1_1")
        self.btn1_2 = QtWidgets.QPushButton(self.groupBox1)
        self.btn1_2.setGeometry(QtCore.QRect(10, 70, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn1_2.setFont(font)
        self.btn1_2.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.btn1_2.setCheckable(False)
        self.btn1_2.setObjectName("btn1_2")
        self.groupBox2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox2.setGeometry(QtCore.QRect(10, 130, 241, 151))
        self.groupBox2.setObjectName("groupBox2")
        self.btn2_1 = QtWidgets.QPushButton(self.groupBox2)
        self.btn2_1.setGeometry(QtCore.QRect(10, 30, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn2_1.setFont(font)
        self.btn2_1.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.btn2_1.setCheckable(False)
        self.btn2_1.setObjectName("btn2_1")
        self.btn2_2 = QtWidgets.QPushButton(self.groupBox2)
        self.btn2_2.setGeometry(QtCore.QRect(10, 70, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn2_2.setFont(font)
        self.btn2_2.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.btn2_2.setCheckable(False)
        self.btn2_2.setObjectName("btn2_2")
        self.btn2_3 = QtWidgets.QPushButton(self.groupBox2)
        self.btn2_3.setGeometry(QtCore.QRect(10, 110, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn2_3.setFont(font)
        self.btn2_3.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.btn2_3.setCheckable(False)
        self.btn2_3.setObjectName("btn2_3")
        self.groupBox3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox3.setGeometry(QtCore.QRect(260, 10, 221, 271))
        self.groupBox3.setObjectName("groupBox3")
        self.btn3_1 = QtWidgets.QPushButton(self.groupBox3)
        self.btn3_1.setGeometry(QtCore.QRect(10, 30, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn3_1.setFont(font)
        self.btn3_1.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.btn3_1.setCheckable(False)
        self.btn3_1.setObjectName("btn3_1")
        self.btn3_2 = QtWidgets.QPushButton(self.groupBox3)
        self.btn3_2.setGeometry(QtCore.QRect(10, 70, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn3_2.setFont(font)
        self.btn3_2.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.btn3_2.setCheckable(False)
        self.btn3_2.setObjectName("btn3_2")
        self.btn3_4 = QtWidgets.QPushButton(self.groupBox3)
        self.btn3_4.setGeometry(QtCore.QRect(10, 230, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn3_4.setFont(font)
        self.btn3_4.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.btn3_4.setCheckable(False)
        self.btn3_4.setObjectName("btn3_4")
        self.groupBox3_3 = QtWidgets.QGroupBox(self.groupBox3)
        self.groupBox3_3.setGeometry(QtCore.QRect(9, 110, 201, 111))
        self.groupBox3_3.setObjectName("groupBox3_3")
        self.label3_3 = QtWidgets.QLabel(self.groupBox3_3)
        self.label3_3.setGeometry(QtCore.QRect(10, 20, 181, 20))
        self.label3_3.setObjectName("label3_3")
        self.comboBox3_3 = QtWidgets.QComboBox(self.groupBox3_3)
        self.comboBox3_3.setGeometry(QtCore.QRect(10, 40, 181, 22))
        self.comboBox3_3.setObjectName("comboBox3_3")
        self.btn3_3 = QtWidgets.QPushButton(self.groupBox3_3)
        self.btn3_3.setGeometry(QtCore.QRect(10, 70, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn3_3.setFont(font)
        self.btn3_3.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.btn3_3.setCheckable(False)
        self.btn3_3.setObjectName("btn3_3")
        self.groupBox4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox4.setGeometry(QtCore.QRect(490, 10, 201, 71))
        self.groupBox4.setObjectName("groupBox4")
        self.btn4 = QtWidgets.QPushButton(self.groupBox4)
        self.btn4.setGeometry(QtCore.QRect(10, 30, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn4.setFont(font)
        self.btn4.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.btn4.setCheckable(False)
        self.btn4.setObjectName("btn4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox1.setTitle(_translate("MainWindow", "1. Histogram Equalization"))
        self.btn1_1.setText(_translate("MainWindow", "1.1 Original image histogram"))
        self.btn1_2.setText(_translate("MainWindow", "1.2 Equalized image histogram"))
        self.groupBox2.setTitle(_translate("MainWindow", "2. Hough Circle Transform and Histogram"))
        self.btn2_1.setText(_translate("MainWindow", "2.1 Hough circle"))
        self.btn2_2.setText(_translate("MainWindow", "2.2 Hue histogram"))
        self.btn2_3.setText(_translate("MainWindow", "2.3 Back projection"))
        self.groupBox3.setTitle(_translate("MainWindow", "3. Camera Calibration"))
        self.btn3_1.setText(_translate("MainWindow", "3.1 Corner detection"))
        self.btn3_2.setText(_translate("MainWindow", "3.2 Intrinsic matrix"))
        self.btn3_4.setText(_translate("MainWindow", "3.4 Distortion matrix"))
        self.groupBox3_3.setTitle(_translate("MainWindow", "3.3 Extrinsic matrix"))
        self.label3_3.setText(_translate("MainWindow", "Select image"))
        self.btn3_3.setText(_translate("MainWindow", "3.3 Extrinsic matrix"))
        self.groupBox4.setTitle(_translate("MainWindow", "4. Augmented Reality"))
        self.btn4.setText(_translate("MainWindow", "4. Augmented Reality"))

